---
apiVersion: v1
kind: Namespace
metadata:
  name: hotdogapi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hotdogapi
  name: hotdogapi
  labels:
    app: hotdogapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotdogapi
  template:
    metadata:
      labels:
        app: hotdogapi
    spec:
      containers:
      - name: hotdogapi
        image: jigglebox/hotdogapi
        imagePullPolicy: Always
        ports:
          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  namespace: hotdogapi
  name: hotdogapi
  labels:
    app: hotdogapi
spec:
  selector:
    app: hotdogapi
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
